### ISSUE TITLE
Suggest adding to build documentation

### ISSUE THREAD

**Issue by royshil** [nocarryr/cyndilib#6]
Excellent project - thank you!
I use it in https://github.com/occ-ai/scoresight

While python 3.12 isn't supported from PyPi I resort to building, and missing some deps before `setup.py`
Suggest adding
```
$ pip install setuptools cython numpy
```
to the build instructions.
Note: this is without `pipenv`.
Will be useful for brand new machines or a CI build.

Thanks!

**Comment by nocarryr** [comment]
Not a bad idea.  And adding a few more pointers on the development side might not hurt either.  Interesting though, I thought the build deps would've been detected from the `pyproject.toml` under its `build-system` section, but maybe not with the setup.py present.

Either way, it should be documented so thanks!  And I meant to add Py3.12 as build target, but forgot before the last release.  Oops!
