### ISSUE TITLE
Tagging a new release

### ISSUE THREAD

**Issue by jcelerier** [nocarryr/cyndilib#9]
Hello ! 
Would it be possible to tag a new release of the library with the latest fixes, so that we can easily leverage it in requirements.txt ?

Thanks ! :)

**Comment by nocarryr** [comment]
@jcelerier I've been meaning to do that.  There are a couple of things I was waiting to finish first, namely typing stubs (.pyi files) to make things easier to work with in IDE's.

I'd like to at least wait and see how #10 looks first if that's ok

**Comment by jcelerier** [comment]
yes definitely ! there's no emergency :) thanks !

**Comment by nocarryr** [comment]
[0.0.4](https://pypi.org/project/cyndilib/0.0.4/) is now live.  Thanks!

**Comment by jcelerier** [comment]
super! @guillaumeriousat this solves our MR issue :)
